//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnlineStore.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product was added to cart successfully!.
        /// </summary>
        public static string Alert_AddProductCartSuccessfully {
            get {
                return ResourceManager.GetString("Alert_AddProductCartSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Btn_Activate {
            get {
                return ResourceManager.GetString("Btn_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string Btn_AddToCart {
            get {
                return ResourceManager.GetString("Btn_AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filters.
        /// </summary>
        public static string Btn_ApplyFilters {
            get {
                return ResourceManager.GetString("Btn_ApplyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string Btn_Deactivate {
            get {
                return ResourceManager.GetString("Btn_Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to products page!.
        /// </summary>
        public static string Btn_NavigationToProductsPage {
            get {
                return ResourceManager.GetString("Btn_NavigationToProductsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Filters.
        /// </summary>
        public static string Btn_ResetFilters {
            get {
                return ResourceManager.GetString("Btn_ResetFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string DropdownValue_Active {
            get {
                return ResourceManager.GetString("DropdownValue_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All products.
        /// </summary>
        public static string DropdownValue_AllProducts {
            get {
                return ResourceManager.GetString("DropdownValue_AllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string DropdownValue_Inactive {
            get {
                return ResourceManager.GetString("DropdownValue_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Stock.
        /// </summary>
        public static string DropdownValue_InStock {
            get {
                return ResourceManager.GetString("DropdownValue_InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Stock.
        /// </summary>
        public static string DropdownValue_OutOfStock {
            get {
                return ResourceManager.GetString("DropdownValue_OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: low to high.
        /// </summary>
        public static string DropdownValue_Sort_PriceAsc {
            get {
                return ResourceManager.GetString("DropdownValue_Sort_PriceAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: high to low.
        /// </summary>
        public static string DropdownValue_Sort_PriceDesc {
            get {
                return ResourceManager.GetString("DropdownValue_Sort_PriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name: A-Z.
        /// </summary>
        public static string DropdownValue_Sort_ProductNameAsc {
            get {
                return ResourceManager.GetString("DropdownValue_Sort_ProductNameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name: Z-A.
        /// </summary>
        public static string DropdownValue_Sort_ProductNameDesc {
            get {
                return ResourceManager.GetString("DropdownValue_Sort_ProductNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active status.
        /// </summary>
        public static string Label_ActiveStatus {
            get {
                return ResourceManager.GetString("Label_ActiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string Label_Availability {
            get {
                return ResourceManager.GetString("Label_Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string Label_Brand {
            get {
                return ResourceManager.GetString("Label_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My shopping Cart.
        /// </summary>
        public static string Label_Cart {
            get {
                return ResourceManager.GetString("Label_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Summary.
        /// </summary>
        public static string Label_cartSummary {
            get {
                return ResourceManager.GetString("Label_cartSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Label_Category {
            get {
                return ResourceManager.GetString("Label_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Products.
        /// </summary>
        public static string Label_FilterProducts {
            get {
                return ResourceManager.GetString("Label_FilterProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price From.
        /// </summary>
        public static string Label_PriceFrom {
            get {
                return ResourceManager.GetString("Label_PriceFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price To.
        /// </summary>
        public static string Label_PriceTo {
            get {
                return ResourceManager.GetString("Label_PriceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Label_ProductName {
            get {
                return ResourceManager.GetString("Label_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting options.
        /// </summary>
        public static string Label_SortOptions {
            get {
                return ResourceManager.GetString("Label_SortOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Label_Test {
            get {
                return ResourceManager.GetString("Label_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cart is empty!.
        /// </summary>
        public static string Msg_EmptyCart {
            get {
                return ResourceManager.GetString("Msg_EmptyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No product found after applying the filters..
        /// </summary>
        public static string Msg_NoProductFoundFilters {
            get {
                return ResourceManager.GetString("Msg_NoProductFoundFilters", resourceCulture);
            }
        }
    }
}
